campusevents/config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :attendees
  resources :locations
  resources :meetings
  resources :sponsors
  resources :events
  resources :sponsors

  root 'events#index'

end

campusevents/app/models/attendee.rb
class Attendee < ActiveRecord::Base
    validates :first_name, :last_name, :email, presence: true

    has_many :subscriptions
    has_many :events, :through => :subscriptions

    def full_name
        ret = first_name + " " +  last_name
    end
end

campusevents/app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]

  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
  end

  # GET /attendees/new
  def new
    @attendee = Attendee.new
  end

  # GET /attendees/1/edit
  def edit
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(attendee_params)

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @attendee, notice: 'Attendee was successfully created.' }
        format.json { render :show, status: :created, location: @attendee }
      else
        format.html { render :new }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1
  # PATCH/PUT /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to attendees_url, notice: 'Attendee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:first_name, :last_name, :email)
    end
end

campusevents/app/helpers/attendees_helper.rb
module AttendeesHelper
end

campusevents/app/views/attendees/_form.html.erb
<%= form_for(@attendee) do |f| %>
    <% if @attendee.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>
            <ul>
                <% @attendee.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="row">
        <div class="col-lg-4 m-l-15">
            <div class="field form-group">
                <%= f.label :first_name %><br>
                <%= f.text_field :first_name, :class => "form-control" %>
            </div>
            <div class="field form-group">
                <%= f.label :last_name %><br>
                <%= f.text_field :last_name, :class => "form-control" %>
            </div>
            <div class="field form-group">
                <%= f.label :email %><br>
                <%= f.text_field :email, :class => "form-control" %>
            </div>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-lg-3">
            <div class="actions text-center">
                <%= f.submit :class => "btn btn-lg btn-success" %>
            </div>
        </div>  
    </div>
<% end %>

campusevents/app/views/attendees/edit.html.erb
<% content_for(:pagetitle) do %>
    Editing <i><%= @attendee.full_name %></i>
<% end %>
    
<% content_for(:pagebuttons) do %>
    <div class="btn-group" style="margin-left: 2%; margin-bottom: 1%;">
        <%= link_to 'Show', @attendee, :class => "btn btn-sm btn-info" %>
        <%= link_to 'Back', attendees_path, :class => "btn btn-sm btn-warning" %>
    </div>
<% end %>

<% content_for(:sidebar) do %>

<% end %>

<%= render 'form' %>
<br/>
<% content_for(:pagebuttons) do %>
  <div class="btn-group" style="margin-left: 2%; margin-bottom: 1%;">
      <%= link_to 'Show', @meeting, :class => "btn btn-sm btn-info" %>
      <%= link_to 'Back', meetings_path, :class => "btn btn-sm btn-warning" %>
  </div>
<% end %>

campusevents/app/views/attendees/index.html.erb
<p id="notice"><%= notice %></p>

  <% content_for(:pagetitle) do %>
    Attendees
  <% end %>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= attendee.first_name %></td>
        <td><%= attendee.last_name %></td>
        <td><%= attendee.email %></td>
        <td class="text-center"><%= link_to 'Show', attendee, :class => "btn btn-info" %></td>
        <td class="text-center"><%= link_to 'Edit', edit_attendee_path(attendee), :class => "btn btn-warning" %></td>
        <td class="text-center"><%= link_to 'Destroy', attendee, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendee', new_attendee_path, :class => "btn btn-lg btn-primary" %>

campusevents/app/views/attendees/new.html.erb
<h1>New Attendee</h1>

<%= render 'form' %>

<%= link_to 'Back', attendees_path %>

campusevents/app/views/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for(:pagetitle) do %>
    <i><%= @attendee.full_name %></i> Details
<% end %>

<% content_for(:pagebuttons) do %>
    <div class="btn-group" style="margin-left: 2%; margin-bottom: 1%;">
        <%= link_to 'Edit', edit_attendee_path(@attendee), :class => "btn btn-sm btn-info" %>
        <%= link_to 'Back', attendees_path, :class => "btn btn-sm btn-warning" %>
    </div>
<% end %>

<% content_for(:sidebar) do %>
    
<% end %>

<p>
  <strong>First name:</strong>
  <%= @attendee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @attendee.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @attendee.email %>
</p>

<br/>