campusevents/config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :attendees
  resources :locations
  resources :meetings
  resources :sponsors
  resources :events
  resources :sponsors

  root 'events#index'

end

campusevents/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Campus Events Manager</title>
  <!-- Put Google Fonts CDN with our the other stylesheets -->
  <link href="https://fonts.googleapis.com/css?family=Lobster+Two:400,700|Lato" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top bg-primary">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Campus Events", :root, :class => "navbar-brand active text-white" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Attendees", attendees_path %></li>
          <li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Locations", locations_path %></li>
          <li><%= link_to "Meetings", meetings_path %></li>
          <li><%= link_to "Sponsors", sponsors_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

<div class="container">
    <div class="row">
        <div class="col-lg-10">            
            <h1><%= yield :pagetitle %><small><%= yield :pagebuttons %></small></h1>            
        </div>        
        <div class="clearfix"></div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <%= yield :layout %>
        </div>
        <div class="col-lg-4">
            <%= yield :sidebar %>
        </div>
    </div> 
</div>

</body>
</html>