concerttickets/config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :purchases
  resources :concerts
  resources :user_sessions
  resources :users

  root 'concerts#index'

  get "login", :to => "user_sessions#new"
  get "logout", :to => "user_sessions#destroy"

  get "purchases/:concert_id/new" => "purchases#new", as: :purchase_tickets

end

concerttickets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Concertickets</title>
  <!-- Put Google Fonts CDN with our the other stylesheets -->
  <link href="https://fonts.googleapis.com/css?family=Lobster+Two:400,700|Lato" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Concert Manager", :root, :class => "navbar-brand active text-white" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to("Concerts", concerts_path) %></li>

          <% if current_user %>
            <% if current_user.has_role? :admin %>
              <li><%= link_to("Venues", venues_path) %></li>
              <li><%= link_to("Users", users_path) %></li>
            <% end %>
            <li><%= link_to("Purchases", purchases_path) %></li>
            <li><%= link_to("Edit profile", edit_user_path(current_user.id)) %></li>
            <li><%= link_to("Logout", logout_path) %></li>
          <% else %>
            <li><%= link_to("Register", new_user_path) %></li>
            <li><%= link_to("Login", login_path) %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h1><%= yield :pagetitle %><small><%= yield :pagebuttons %></small></h1>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="row">
      <%= yield :layout %>
    </div>
  </div>

</body>
</html>